### ISSUE TITLE
please update your license to a vaild SPDX identifier

### ISSUE THREAD

**Issue by HansHammel** [rmustacc/node-ctype#62]
it's just "license":"MIT" in your case

**Comment by rmustacc** [comment]
It's already there, see https://github.com/rmustacc/node-ctype/blob/master/package.json#L13. Maybe someone hasn't updated a dep to include it?

**Comment by HansHammel** [comment]
Yes but its invalid see the docs at https://docs.npmjs.com/files/package.json whete it says:
Some old packages used license objects or a "licenses" property containing an array of license objects:
```json
// Not valid metadata
{ "license" :
  { "type" : "ISC"
  , "url" : "http://opensource.org/licenses/ISC"
  }
}

// Not valid metadata
{ "licenses" :
  [
    { "type": "MIT"
    , "url": "http://www.opensource.org/licenses/mit-license.php"
    }
  , { "type": "Apache-2.0"
    , "url": "http://opensource.org/licenses/apache2.0.php"
    }
  ]
}
```
Those styles are now deprecated. Instead, use SPDX expressions, like this:
```json
{ "license": "ISC" }

{ "license": "(MIT OR Apache-2.0)" }
```

**Comment by rmustacc** [comment]
Oh, I see. You're asking to get rid of the older licenses block, is that right? As it appears that the license block seems correct and that MIT is a valid SPDX string based on my reading. Does that match what you're seeing?

**Comment by HansHammel** [comment]
you want to keep the old licenses array!? well, ok.

**Comment by rmustacc** [comment]
On 1/9/17 9:20 , Oliver Bleckmann wrote:
> you want to keep the old licenses array!? well, ok.
> 

I didn't understand that you were referring to the licenses array as
being the problem initially. I thought there was something wrong with
the string 'MIT' in the 'license' object entry. We can look at removing
it, though it was mostly added at the request of others in #51.

**Comment by HansHammel** [comment]
>It's already there

Maybe I missed that out. It's all fine. Maybe I have analysed an old package version. My program was complainingabout a missing license, I thought it was because of the old standard present, but if others insist...
